#!/bin/bash
set -e

# JWT Secret Configuration Script for Xcode Cloud
# This script generates the Base.xcconfig file with JWT secret

# -------------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------------

# Define paths relative to the project root
CONFIG_DIR="Configuration"
OUTPUT_FILE="$CONFIG_DIR/Base.xcconfig"
TEMPLATE_FILE="$CONFIG_DIR/Base.template.xcconfig."

# -------------------------------------------------------------------------
# Main Script
# -------------------------------------------------------------------------

echo "========================================================"
echo "  JWT Secret Configuration for Xcode Cloud"
echo "========================================================"

# Create Configuration directory if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
    echo "Creating configuration directory..."
    mkdir -p "$CONFIG_DIR"
fi

# Check if JWT_SECRET environment variable is set in Xcode Cloud
if [ -z "$JWT_SECRET" ]; then
    echo "Warning: JWT_SECRET environment variable is not set."
    echo "Using placeholder value for development purposes."
    JWT_SECRET="development-placeholder-jwt-secret"
fi

# Create the Base.xcconfig file from template if it exists
if [ -f "$TEMPLATE_FILE" ]; then
    echo "Generating $OUTPUT_FILE from template..."
    cp "$TEMPLATE_FILE" "$OUTPUT_FILE"
    
    # Replace the JWT_SECRET placeholder with actual value
    sed -i.bak "s/\$(JWT_SECRET)/$JWT_SECRET/g" "$OUTPUT_FILE"
    rm -f "$OUTPUT_FILE.bak"
else
    # Create the file directly if template doesn't exist
    echo "Creating $OUTPUT_FILE directly..."
    cat > "$OUTPUT_FILE" << EOF
// Base.xcconfig
// Generated by setup_jwt_config.sh - DO NOT EDIT MANUALLY
// Add this file to .gitignore

// JWT Secret for OpenAI proxy authentication
JWT_SECRET = $JWT_SECRET

// App version information
MARKETING_VERSION = 0.4.0
CURRENT_PROJECT_VERSION = 1
EOF
fi

echo "Base.xcconfig successfully generated."
echo "========================================================"
