import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .all,
    swiftVersion: "6.0.0",
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(),
        disableAutogeneratedSchemes: false
    )
)
