# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_tests do
    run_tests(
      project: "MovingBox.xcodeproj",
      scheme: "MovingBoxTests",
      devices: ["iPhone 17 Pro"],
      derived_data_path: "DerivedData",
      clean: true,
      destination: "generic/platform=iOS Simulator"
    )
  end

  desc "Build the app"
  lane :build do
    build_app(
      project: "MovingBox.xcodeproj",
      scheme: "MovingBox",
      configuration: "Debug",
      derived_data_path: "DerivedData",
      destination: "generic/platform=iOS Simulator",
      skip_package_ipa: true,
      skip_package_pkg: true,
      skip_build_archive: true
    )
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    # Set simulator boot timeout
    ENV["SNAPSHOT_SIMULATOR_WAIT_FOR_BOOT_TIMEOUT"] = "10"
    
    # Reset simulators
    reset_simulator_contents
    
    # Capture screenshots
    capture_ios_screenshots(
      output_directory: "./fastlane/screenshots/light"
    )

    # Capture dark screenshots
    capture_ios_screenshots(
      dark_mode: true,
      output_directory: "./fastlane/screenshots/dark"
    )
    
    # Generate frames for both light and dark mode
    generate_frames(mode: "light")
  end

  desc "Generate frames for existing screenshots"
  lane :generate_frames do |options|
    # Set default mode to light if not specified
    mode = options[:mode] || "light"
    
    frameit(
      path: "./fastlane/screenshots/#{mode}",
    )
  end

  desc "Run UI Tests on multiple devices"
  lane :ui_tests do
    # First reset simulators to ensure clean state
    reset_simulator_contents

    # Run tests on each device
    run_tests(
      project: "MovingBox.xcodeproj",
      scheme: "MovingBoxUITests",
      devices: ["iPhone 14 Pro (18.4)",
                "iPhone 14 Pro Max (18.4)"
            ],
      buildlog_path: "./fastlane/fastlane-buildlog",
      derived_data_path: "DerivedData"
    )
  end

  desc "Generate marketing banner"
  lane :banner do
    script_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "..", "..", "MothersoundLLC", "02-marketing", "assets"))
    sh("bash #{script_dir}/generate_banner.sh")
  end
end
