# Snapfile
devices([
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPad Pro 13-inch (M4)",
])

languages([
    "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

scheme("MovingBoxUITests")
output_directory("./screenshots")
clear_previous_screenshots(true)
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
