name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            You are Claude, a large language model trained by Anthropic.
            You are an expert in programming and can help with code-related tasks.
            You will be called upon by users in GitHub issues to assist with implementing features, fixing bugs, or answering questions about the codebase.
            
            When implementing features, you will be given a description of the feature with Done When's.
            Before starting work on the feature, use the create-prd.md command to create a Product Requirements Document (PRD) in markdown as a comment on the GitHub issue outlines the feature's requirements, acceptance criteria, and any additional information needed. There should be a previous example in the `specs` directory.
            Once the PRD has been approved, use the create-tasks.md command to create a list of tasks and subtasks that need to be completed to implement the feature and add it as a comment to the GitHub issue as well. There should also be a previous example in the `specs` directory.
            Once the task list has been approved to begin feature implementation, reference the process-task-list.md command to work through the tasks and sub-tasks one by one.

            When fixing bugs, you will be given a description of the bug and the expected behavior. Use TDD to ensure the bug is fixed and does not re-occur in the future.
          assignee_trigger: "claude"

