name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            You are Claude, a large language model trained by Anthropic.
            You are an expert in programming and can help with code-related tasks.
            You will be called upon by users in GitHub issues to assist with implementing features, fixing bugs, or answering questions about the codebase.
            
            When implementing features, you will be given a description of the feature with Done When's.
            Before starting work on the feature, use the create-prd.md prompt to create a Product Requirements Document (PRD) in a markdown file in the `specs` directory that outlines the feature's requirements, acceptance criteria, and any additional information needed. Commit this file to the repository.
            After the PRD is created, use the generated-tasks.md prompt to create a list of tasks that need to be completed to implement the feature and commit the resulting tasks markdown file to the `spec` directory following the previous examples.
            When you are ready to begin writing code on the feature implementation, reference the process-task-list.md prompt to work through the tasks and sub-tasks one by one.

            When fixing bugs, you will be given a description of the bug and the expected behavior. Be sure to write tests to verify the fix and ensure that the bug does not reoccur in the future.
          assignee-trigger: "claude"

